version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mkdir -p $CODEBUILD_SRC_DIR/source1
      - cd $CODEBUILD_SRC_DIR/source1
      - touch file1
      - mkdir -p $CODEBUILD_SRC_DIR/source2
      - cd $CODEBUILD_SRC_DIR/source2
      - touch file2
  post_build:
    commands:
      - echo Build completed on `date`
      - printenv
artifacts:
  files:
    - target/messageUtil-1.0.jar
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR/source1
      files:
        - file1
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR/source2
      files:
        - file2