version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mkdir -p secondary-output/testdir1
      - touch secondary-output/testdir1/file1
      - mkdir -p secondary-output/testdir2
      - touch secondary-output/testdir2/file2
  post_build:
    commands:
      - echo Build completed on `date`
      - printenv
artifacts:
  files:
    - target/messageUtil-1.0.jar
    - secondary-output/**/*
  secondary-artifacts:
    artifact1:
      base-directory: secondary-output/testdir1
      files:
        - file1
    artifact2:
      base-directory: secondary-output/testdir2
      files:
        - file2