version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mkdir -p target/secondary-output/testdir1
      - touch target/secondary-output/testdir1/file1
      - mkdir -p target/secondary-output/testdir2
      - touch target/secondary-output/testdir2/file2
  post_build:
    commands:
      - echo Build completed on `date`
      - printenv
artifacts:
  files:
    - target/**/*
  secondary-artifacts:
    artifact1:
      base-directory: target/secondary-output/testdir1
      files:
        - file1
    artifact2:
      base-directory: target/secondary-output/testdir2
      files:
        - file2