version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - printenv
artifacts:
  files:
    - target-test/messageUtil-1.0.jar
  secondary-artifacts:
    artifact1:
      files:
        - target/artifact1/messageUtil-1-1.0.jar
      discard-paths: yes
    artifact2:
      files:
        - target/artifact2/messageUtil-2-1.0.jar
      discard-paths: yes